on: push

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.R_LIBS_USER }}
            /usr/local/lib/R/site-library
            /usr/lib/R/site-library
            /usr/lib/R/library
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/NAMESPACE', '**/*.R', '**/*.r') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1' # Stellen Sie sicher, dass Sie hier eine gültige R-Version angeben, die Ihrer Anforderung entspricht

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::readr
          cache-version: 1

      - name: Run main.r
        run: Rscript -e 'source("main.r")'

      - name: Commit outputs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          branch_name=$(git symbolic-ref --short HEAD)
          git add ./output/*
          git commit -m "Automatically update output" -a || echo "No changes to commit"
          git push