on:
  push:
    branches: main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: run main.r
        run: Rscript -e 'source("main.r")'

      - name: Run the Action
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Output neu erstellt"
          force: false
