on:
  push:
    branches: main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: run main.r
        run: Rscript -e 'source("main.r")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output
          git commit -m 'output' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
